#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# deploy.sh — runs ON the VM (Linux).
# Uploaded automatically by deploy.ps1 from Windows.
# You can also run it manually after SSH-ing in:
#   cd ~/meatyboys && bash deploy.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e
APP_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$APP_DIR"

# ── virtual environment ───────────────────────────────────────────────────────
if [ ! -d ".venv" ]; then
    echo "[setup] Creating virtual environment..."
    python3 -m venv .venv
fi
source .venv/bin/activate

# ── dependencies ──────────────────────────────────────────────────────────────
echo "[setup] Installing dependencies..."
pip install -q -r requirements.txt

# ── data directories ──────────────────────────────────────────────────────────
mkdir -p data playerfiles

# Initialise state files on first deploy so the app doesn't crash on cold start
[ -f playerfiles/time.txt ]       || echo '{"time":"1970-01-01T00:00:00.000Z","usr":"","snake":"up"}' > playerfiles/time.txt
[ -f playerfiles/allplayers.txt ] || echo '[]'  > playerfiles/allplayers.txt
[ -f playerfiles/users.txt ]      || echo '{}' > playerfiles/users.txt

# ── initial data seed (first deploy only) ─────────────────────────────────────
if [ ! -f data/round.json ]; then
    echo "[setup] No data found — running fetch scripts to seed initial data..."
    python3 scripts/fetch.py
fi

# ── install cron jobs ─────────────────────────────────────────────────────────
echo "[setup] Installing cron jobs..."
PYTHON="$APP_DIR/.venv/bin/python3"

# Remove any existing meatyboys cron entries then re-add with correct paths
(crontab -l 2>/dev/null | grep -v 'meatyboys') | crontab - || true
(crontab -l 2>/dev/null; cat <<CRON
# Meaty Boys Cup — auto-generated by deploy.sh
*/3 * * * 5,6,0,1 $PYTHON $APP_DIR/scripts/get_player_scores.py >> $APP_DIR/cron.log 2>&1
*/120 * * * 2,3,4 $PYTHON $APP_DIR/scripts/get_player_scores.py >> $APP_DIR/cron.log 2>&1
*/120 * * * 2,3,4 $PYTHON $APP_DIR/scripts/save_draft.py >> $APP_DIR/cron.log 2>&1
*/60 * * * 0,1,5,6 $PYTHON $APP_DIR/scripts/save_draft.py >> $APP_DIR/cron.log 2>&1
*/20 * * * 4,5,6,0,1 $PYTHON $APP_DIR/scripts/save_round.py >> $APP_DIR/cron.log 2>&1
* * * * 5,6,0 $PYTHON $APP_DIR/scripts/save_scoreboard.py >> $APP_DIR/cron.log 2>&1
*/120 * * * 1,2,3,4 $PYTHON $APP_DIR/scripts/save_scoreboard.py >> $APP_DIR/cron.log 2>&1
0 17 * * * $PYTHON $APP_DIR/scripts/get_cookie.py >> $APP_DIR/cron.log 2>&1
*/120 * * * 2,3,4 $PYTHON $APP_DIR/scripts/save_leaguetable.py >> $APP_DIR/cron.log 2>&1
*/60 * * * 0,1,5,6 $PYTHON $APP_DIR/scripts/save_leaguetable.py >> $APP_DIR/cron.log 2>&1
CRON
) | crontab -
echo "[setup] Cron jobs installed."

# ── stop any running instance ─────────────────────────────────────────────────
echo "[deploy] Stopping old gunicorn (if running)..."
pkill -f "gunicorn.*app:app" 2>/dev/null || true
sleep 1

# ── read PORT and HOST from .env ──────────────────────────────────────────────
APP_PORT=$(grep '^PORT=' .env | head -1 | cut -d'=' -f2 | tr -d '"')
APP_HOST=$(grep '^HOST=' .env | head -1 | cut -d'=' -f2 | tr -d '"')
APP_PORT=${APP_PORT:-5000}
APP_HOST=${APP_HOST:-0.0.0.0}

# ── start gunicorn ────────────────────────────────────────────────────────────
echo "[deploy] Starting gunicorn on ${APP_HOST}:${APP_PORT}..."
nohup .venv/bin/gunicorn \
    -w 1 \
    --threads 4 \
    -b "${APP_HOST}:${APP_PORT}" \
    --access-logfile "$APP_DIR/gunicorn.log" \
    app:app \
    >> "$APP_DIR/gunicorn.log" 2>&1 &

echo ""
echo "✓ App started — http://$(hostname -I | awk '{print $1}'):${APP_PORT}"
echo "  Logs:  tail -f $APP_DIR/gunicorn.log"
echo "  Crons: crontab -l"
